apiVersion: v1
kind: Service
metadata:
  name: api-performance-analyzer-service
spec:
  type: NodePort
  selector:
    app: api-performance-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007